---


   #HINT: Possible approach: Check available version before
- name: Get fuse-overlayfs version available from apt cache
  become: true
  shell: apt-cache policy fuse-overlayfs | grep andidat | grep -Eo '[^[:blank:]]+$' | grep -Eo '^[^-]+' | cat
  register: fuseOverlayFsAvailableVersionShellResult

- name: Install latest static version of fuse-overlayfs executable
  when: >
    fuseOverlayFsAvailableVersionShellResult.stdout|regex_search('[0-9]+(?:\.[0-9]+){1,2}') == none
    or fuseOverlayFsAvailableVersionShellResult.stdout is version('1.0.0','<')
  block:

      # Latest version result: fuseOverlayFsSourceGithubResult.recommended_version
    - name: Determine fuse-overlayfs latest release version
      maveno_de.forks_collection.source_github:
        owner: containers
        repo: fuse-overlayfs
      environment:
        SSL_CERT_DIR: /etc/ssl/certs
        REQUESTS_CA_BUNDLE: "{{ forksSystemCaCertificatesFilePath }}"
      register: fuseOverlayFsSourceGithubResult
    
    - name: Download and install latest static version of fuse-overlayfs executable
      become: true
      get_url:
        url: "https://github.com/containers/fuse-overlayfs/releases/download/v{{ fuseOverlayFsSourceGithubResult.recommended_version }}/fuse-overlayfs-{{ fuseOverlayFsArchitectureLookupTable[forksSystemArchitecture] }}"
        dest: /usr/bin/
        owner: root
        group: root
        mode: 0755
      environment:
        SSL_CERT_DIR: /etc/ssl/certs
      register: getUrlResult
      until: getUrlResult is success
      retries: 10
      delay: 30

    - name: Rename fuse-overlayfs executable executable
      become: true
      shell: "mv \"{{ getUrlResult.dest }}\" /usr/bin/fuse-overlayfs"


- name: Install latest static vesion of fuse-overlayfs
  when: 
    - fuseOverlayFsAvailableVersionShellResult.stdout|regex_search('[0-9]+(?:\.[0-9]+){1,2}') != none
    - fuseOverlayFsAvailableVersionShellResult.stdout is version('1.0.0','>=')
  block:

    - name: Switch temporarily to system python
      set_fact: 
        tempPythonInterpreter: >-
          {{ ansible_python_interpreter
          | default(forksSystemPythonInterpreter) }}
    - set_fact: 
        ansible_python_interpreter: "{{ forksSystemPythonInterpreter }}"
    ###
    
    - name: Install latest version of fuse-overlayfs as apt package
      become: true
      apt:
        state: latest
        pkg: fuse-overlayfs
        cache_valid_time: 10800
    
    ###
    - name: Switch back to framework python venv
      set_fact: 
        ansible_python_interpreter: "{{ tempPythonInterpreter }}"
