---


- name: Fix permissions for local docker directory
  become: true
  file:
    path: "{{ forksDockerHomeDirectory }}/.local/share/docker"
    recurse: yes
    follow: no
    owner: "{{ forksDockerSystemUsername }}"
    group: "{{ forksDockerSystemUsername }}"
    mode: u=rwX,g=rX,o=

- name: "Get {{ forksDockerIdentifier|capitalize }} running containers"
  become: true
  become_user: "{{ forksDockerSystemUsername }}"
  community.docker.docker_host_info:
    containers: yes
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"
  changed_when: false
  failed_when: false
  ignore_errors: true
  register: forkDockerHostInfoResult

- name: "Stop {{ forksDockerIdentifier|capitalize }} running containers"
  when: "'containers' in forkDockerHostInfoResult.keys()"
  become: true
  become_user: "{{ forksDockerSystemUsername }}"
  community.docker.docker_container:
    name: "{{ forkContainerItem }}"
    state: stopped
    container_default_behavior: no_defaults
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"
  loop: "{{ forkDockerHostInfoResult.containers | map(attribute='Id') | list }}"
  loop_control:
    loop_var: forkContainerItem


- name: "Remove rootless docker for user {{ forksDockerSystemUsername }}"
  become: true
  become_user: "{{ forksDockerSystemUsername }}"
  shell: dockerd-rootless-setuptool.sh uninstall
  args:
    chdir: "{{ forksDockerHomeDirectory }}"
    executable: /bin/bash
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"
  failed_when: no

- name: "Remove docker data for user {{ forksDockerSystemUsername }}"
  become: true
  file:
    path: "{{ forksDockerHomeDirectory }}/.local/share/docker"
    state: absent

- name: Disable services for context user
  become: true
  shell: "loginctl disable-linger {{ forksDockerSystemUsername }}"
  args:
    removes: "/var/lib/systemd/linger/{{ forksDockerSystemUsername }}"


...
